### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [FoxFurry/PBL-2020-DEPLOYMENT#1]
Hi,<br><br>url : https://github.com/FoxFurry/PBL-2020-DEPLOYMENT/blob/b1133a7136d2a8a1855b2a5031433ec5dbb1b434/plb-2020-i-c999165656c3.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by FoxFurry** [comment]
Thanks, man! Was added by accident

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
